import json
import logging
import math
import os
import socket
import sqlite3
import tempfile
import time
import uuid
from contextlib import closing
from functools import wraps
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from flask import Flask, current_app, g, jsonify, request, send_from_directory, session
from werkzeug.security import check_password_hash, generate_password_hash


LOGGER = logging.getLogger("tangamandapio.api")


def create_app(test_config=None):
    static_folder = Path(__file__).parent / "static"
    app = Flask(__name__, static_folder=str(static_folder), static_url_path="")
    app.config.from_mapping(
        DATABASE_URL=os.getenv("DATABASE_URL", "").strip(),
        DATABASE_PATH=os.getenv(
            "DATABASE_PATH", str(Path(tempfile.gettempdir()) / "tangamandapio.db")
        ),
        AZURE_FULFILLMENT_URL=os.getenv("AZURE_FULFILLMENT_URL", ""),
        AZURE_FUNCTION_KEY=os.getenv("AZURE_FUNCTION_KEY", ""),
        AUTO_DISPATCH_EVENTS=os.getenv("AUTO_DISPATCH_EVENTS", "true").lower()
        in {"1", "true", "yes"},
        SECRET_KEY=os.getenv("APP_SESSION_SECRET", "development-only-change-me"),
        SESSION_COOKIE_HTTPONLY=True,
        SESSION_COOKIE_SAMESITE="Lax",
        SESSION_COOKIE_SECURE=os.getenv("SESSION_COOKIE_SECURE", "false").lower()
        in {"1", "true", "yes"},
        BOOTSTRAP_ADMIN_USERNAME=os.getenv(
            "BOOTSTRAP_ADMIN_USERNAME", "admin@tangamandapio.local"
        ),
        BOOTSTRAP_ADMIN_PASSWORD=os.getenv("BOOTSTRAP_ADMIN_PASSWORD", ""),
        MAX_CONTENT_LENGTH=1024 * 1024,
    )

    if test_config:
        app.config.update(test_config)

    database_path = configured_database_target(app.config)
    if not is_postgresql(database_path):
        Path(database_path).parent.mkdir(parents=True, exist_ok=True)
    initialize_database(database_path)
    ensure_portal_bootstrap(app, database_path)
    app.extensions["metrics"] = {
        "requests_total": 0,
        "orders_created_total": 0,
        "outbox_delivered_total": 0,
        "outbox_failed_total": 0,
    }

    @app.before_request
    def start_request_observation():
        g.request_started_at = time.perf_counter()
        g.request_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())

    @app.after_request
    def secure_and_observe(response):
        app.extensions["metrics"]["requests_total"] += 1
        response.headers["X-Request-ID"] = g.get("request_id", str(uuid.uuid4()))
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Referrer-Policy"] = "no-referrer"
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; base-uri 'self'; object-src 'none'; "
            "frame-ancestors 'none'; form-action 'self'; script-src 'self'; "
            "style-src 'self'"
        )
        response.headers["Cache-Control"] = "no-store"
        if request.is_secure:
            response.headers["Strict-Transport-Security"] = (
                "max-age=31536000; includeSubDomains"
            )
        LOGGER.info(
            json.dumps(
                {
                    "event": "http_request",
                    "request_id": response.headers["X-Request-ID"],
                    "method": request.method,
                    "path": request.path,
                    "status": response.status_code,
                    "duration_ms": round(
                        (time.perf_counter() - g.get("request_started_at", time.perf_counter()))
                        * 1000,
                        2,
                    ),
                    "instance": socket.gethostname(),
                }
            )
        )
        return response

    @app.get("/metrics")
    def metrics():
        values = app.extensions["metrics"]
        lines = [
            "# HELP tangamandapio_http_requests_total Total HTTP responses generated by the API.",
            "# TYPE tangamandapio_http_requests_total counter",
            f"tangamandapio_http_requests_total {values['requests_total']}",
            "# HELP tangamandapio_orders_created_total Orders durably created in the local outbox demo.",
            "# TYPE tangamandapio_orders_created_total counter",
            f"tangamandapio_orders_created_total {values['orders_created_total']}",
            "# HELP tangamandapio_outbox_events_total Outbox delivery attempts grouped by result.",
            "# TYPE tangamandapio_outbox_events_total counter",
            f"tangamandapio_outbox_events_total{{result=\"delivered\"}} {values['outbox_delivered_total']}",
            f"tangamandapio_outbox_events_total{{result=\"failed\"}} {values['outbox_failed_total']}",
        ]
        return "\n".join(lines) + "\n", 200, {"Content-Type": "text/plain; version=0.0.4"}

    @app.post("/api/auth/login")
    def login():
        payload = request.get_json(silent=True) or {}
        username = str(payload.get("username", "")).strip().lower()
        password = str(payload.get("password", ""))
        if not username or not password:
            return jsonify(error="credentials_required"), 400
        with connect(database_path) as connection:
            row = connection.execute(
                """
                SELECT id, username, password_hash, role, company_id, active
                FROM portal_users WHERE username = ?
                """,
                (username,),
            ).fetchone()
        if row is None or not row["active"] or not check_password_hash(row["password_hash"], password):
            LOGGER.warning(json.dumps({"event": "login_denied", "username": username, "request_id": g.request_id}))
            return jsonify(error="invalid_credentials"), 401
        session.clear()
        session["portal_user_id"] = row["id"]
        write_audit(database_path, row["id"], "auth.login", "portal_user", row["id"])
        return jsonify(user=portal_user(database_path, row["id"]))

    @app.post("/api/auth/logout")
    def logout():
        user = current_portal_user(database_path)
        if user:
            write_audit(database_path, user["id"], "auth.logout", "portal_user", user["id"])
        session.clear()
        return "", 204

    @app.get("/api/auth/session")
    def session_status():
        user = current_portal_user(database_path)
        if user is None:
            return jsonify(authenticated=False), 200
        return jsonify(authenticated=True, user=user)

    @app.get("/api")
    def index():
        return jsonify(
            service="Tangamandapio Cloud Demo",
            instance=socket.gethostname(),
            endpoints=["/health", "/ready", "/api/orders", "/api/multicloud"],
        )

    @app.get("/")
    def web_index():
        if (static_folder / "index.html").is_file():
            return send_from_directory(static_folder, "index.html")
        return index()

    @app.get("/health")
    def health():
        database_status = "ok"
        try:
            with connect(database_path) as connection:
                connection.execute("SELECT 1").fetchone()
        except Exception:
            database_status = "error"

        status_code = 200 if database_status == "ok" else 503
        return (
            jsonify(
                status="ok" if status_code == 200 else "degraded",
                database=database_status,
                instance=socket.gethostname(),
                timestamp=datetime.now(timezone.utc).isoformat(),
            ),
            status_code,
        )

    @app.get("/ready")
    def ready():
        try:
            with connect(database_path) as connection:
                connection.execute("SELECT 1").fetchone()
            return jsonify(status="ready", dependencies={"database": "ok"})
        except Exception:
            return jsonify(status="not_ready", dependencies={"database": "error"}), 503

    @app.get("/api/orders")
    @require_roles("customer", "sales", "warehouse", "operations", "admin", "auditor")
    def list_orders():
        user = g.portal_user
        query = """
            SELECT o.id, o.customer, o.total, o.reference, o.status, o.created_at,
                   c.name AS company, creator.username AS created_by
            FROM orders AS o
            LEFT JOIN companies AS c ON c.id = o.company_id
            LEFT JOIN portal_users AS creator ON creator.id = o.created_by
        """
        params = ()
        if user["role"] == "customer":
            query += " WHERE o.company_id = ?"
            params = (user["company_id"],)
        query += " ORDER BY o.id DESC LIMIT 50"
        with connect(database_path) as connection:
            rows = connection.execute(query, params).fetchall()
        return jsonify([dict(row) for row in rows])

    @app.post("/api/orders")
    @require_roles("customer", "sales", "admin")
    def create_order():
        payload = request.get_json(silent=True) or {}
        customer = str(payload.get("customer", "")).strip()
        reference = str(payload.get("reference", "")).strip()
        user = g.portal_user

        try:
            total = float(payload.get("total"))
        except (TypeError, ValueError):
            total = -1

        if (
            not customer
            or len(customer) > 120
            or not math.isfinite(total)
            or total < 0
            or total > 1_000_000
            or len(reference) > 80
        ):
            return (
                jsonify(
                    error="customer (1-120 caracteres) y total (0-1000000) son obligatorios"
                ),
                400,
            )

        created_at = datetime.now(timezone.utc).isoformat()
        with connect(database_path) as connection:
            order_id = insert_and_return_id(
                connection,
                """
                INSERT INTO orders (customer, total, created_at, company_id, created_by, reference, status)
                VALUES (?, ?, ?, ?, ?, ?, 'created')
                """,
                (customer, total, created_at, user["company_id"], user["id"], reference or None),
            )
            event_id = f"evt-{uuid.uuid4().hex}"
            event_payload = {
                "event_id": event_id,
                "event_type": "order.created",
                "schema_version": "1.0",
                "source": "aws-order-core",
                "occurred_at": created_at,
                "order": {
                    "id": order_id,
                    "customer": customer,
                    "total": total,
                    "created_at": created_at,
                },
            }
            connection.execute(
                """
                INSERT INTO outbox_events(event_id, order_id, payload, status, attempts, created_at)
                VALUES (?, ?, ?, 'pending', 0, ?)
                """,
                (event_id, order_id, json.dumps(event_payload, separators=(",", ":")), created_at),
            )
            connection.commit()

        app.extensions["metrics"]["orders_created_total"] += 1
        write_audit(
            database_path,
            user["id"],
            "order.create",
            "order",
            order_id,
            {"company_id": user["company_id"], "reference": reference},
        )
        delivery = {"status": "pending", "event_id": event_id}
        if app.config["AUTO_DISPATCH_EVENTS"]:
            delivery = dispatch_outbox_event(app, database_path, event_id)

        return (
            jsonify(
                id=order_id,
                customer=customer,
                total=total,
                reference=reference or None,
                status="created",
                created_at=created_at,
                instance=socket.gethostname(),
                fulfillment=delivery,
            ),
            201,
        )

    @app.get("/api/outbox")
    @require_roles("operations", "admin", "auditor", "warehouse")
    def list_outbox():
        with connect(database_path) as connection:
            rows = connection.execute(
                """
                SELECT event_id, order_id, status, attempts, last_error, created_at, delivered_at
                FROM outbox_events ORDER BY created_at DESC LIMIT 30
                """
            ).fetchall()
        return jsonify([dict(row) for row in rows])

    @app.post("/api/outbox/<event_id>/retry")
    @require_roles("operations", "admin")
    def retry_outbox(event_id):
        delivery = dispatch_outbox_event(app, database_path, event_id)
        if delivery.get("status") == "not_found":
            return jsonify(error="event_not_found"), 404
        write_audit(
            database_path,
            g.portal_user["id"],
            "outbox.retry",
            "outbox_event",
            event_id,
            {"result": delivery.get("status")},
        )
        return jsonify(delivery)

    @app.get("/api/dashboard")
    @require_roles("customer", "sales", "warehouse", "operations", "admin", "auditor")
    def dashboard():
        user = g.portal_user
        with connect(database_path) as connection:
            order_query = "SELECT COUNT(*) AS count FROM orders"
            params = ()
            if user["role"] == "customer":
                order_query += " WHERE company_id = ?"
                params = (user["company_id"],)
            order_count = connection.execute(order_query, params).fetchone()["count"]
            pending = connection.execute(
                "SELECT COUNT(*) AS count FROM outbox_events WHERE status != 'delivered'"
            ).fetchone()["count"]
            delivered = connection.execute(
                "SELECT COUNT(*) AS count FROM outbox_events WHERE status = 'delivered'"
            ).fetchone()["count"]
        return jsonify(
            orders=order_count,
            outbox={"pending": pending, "delivered": delivered},
            role=user["role"],
            company=user["company"],
        )

    @app.get("/api/admin/users")
    @require_roles("admin")
    def list_users():
        with connect(database_path) as connection:
            rows = connection.execute(
                """
                SELECT u.id, u.username, u.role, u.active, u.created_at, c.name AS company
                FROM portal_users AS u JOIN companies AS c ON c.id = u.company_id
                ORDER BY u.id DESC
                """
            ).fetchall()
        return jsonify([dict(row) for row in rows])

    @app.post("/api/admin/companies")
    @require_roles("admin")
    def create_company():
        """Provision an isolated B2B tenant before assigning its users.

        This deliberately remains an administrator-only operation: a user must
        never select an arbitrary tenant while registering an account.
        """
        payload = request.get_json(silent=True) or {}
        name = str(payload.get("name", "")).strip()
        slug = str(payload.get("slug", "")).strip().lower()
        if (
            not name
            or len(name) > 160
            or not slug
            or len(slug) > 80
            or any(character not in "abcdefghijklmnopqrstuvwxyz0123456789-" for character in slug)
        ):
            return jsonify(error="invalid_company_payload"), 400
        with connect(database_path) as connection:
            try:
                company_id = insert_and_return_id(
                    connection,
                    "INSERT INTO companies(name, slug, created_at) VALUES (?, ?, ?)",
                    (name, slug, datetime.now(timezone.utc).isoformat()),
                )
                connection.commit()
            except Exception as error:
                if is_integrity_error(error):
                    return jsonify(error="company_slug_already_exists"), 409
                raise
        write_audit(
            database_path,
            g.portal_user["id"],
            "company.create",
            "company",
            company_id,
            {"slug": slug},
        )
        return jsonify(id=company_id, name=name, slug=slug), 201

    @app.get("/api/admin/companies")
    @require_roles("admin")
    def list_companies():
        with connect(database_path) as connection:
            rows = connection.execute(
                """
                SELECT c.id, c.name, c.slug, c.created_at, COUNT(u.id) AS users
                FROM companies AS c
                LEFT JOIN portal_users AS u ON u.company_id = c.id
                GROUP BY c.id, c.name, c.slug, c.created_at
                ORDER BY c.name COLLATE NOCASE
                """
            ).fetchall()
        return jsonify([dict(row) for row in rows])

    @app.post("/api/admin/users")
    @require_roles("admin")
    def create_user():
        payload = request.get_json(silent=True) or {}
        username = str(payload.get("username", "")).strip().lower()
        password = str(payload.get("password", ""))
        role = str(payload.get("role", "")).strip().lower()
        company_id = payload.get("company_id") or g.portal_user["company_id"]
        if not username or len(username) > 160 or len(password) < 12 or role not in PORTAL_ROLES:
            return jsonify(error="invalid_user_payload"), 400
        with connect(database_path) as connection:
            company = connection.execute("SELECT id FROM companies WHERE id = ?", (company_id,)).fetchone()
            if company is None:
                return jsonify(error="company_not_found"), 400
            try:
                user_id = insert_and_return_id(
                    connection,
                    """
                    INSERT INTO portal_users(username, password_hash, role, company_id, active, created_at)
                    VALUES (?, ?, ?, ?, 1, ?)
                    """,
                    (
                        username,
                        generate_password_hash(password),
                        role,
                        company_id,
                        datetime.now(timezone.utc).isoformat(),
                    ),
                )
                connection.commit()
            except Exception as error:
                if is_integrity_error(error):
                    return jsonify(error="username_already_exists"), 409
                raise
        write_audit(
            database_path,
            g.portal_user["id"],
            "user.create",
            "portal_user",
            user_id,
            {"role": role, "company_id": company_id},
        )
        return jsonify(user=portal_user(database_path, user_id)), 201

    @app.get("/api/audit")
    @require_roles("admin", "operations", "auditor")
    def audit_log():
        with connect(database_path) as connection:
            rows = connection.execute(
                """
                SELECT a.id, a.action, a.subject_type, a.subject_id, a.detail, a.created_at,
                       COALESCE(u.username, 'system') AS actor
                FROM audit_log AS a LEFT JOIN portal_users AS u ON u.id = a.user_id
                ORDER BY a.id DESC LIMIT 100
                """
            ).fetchall()
        results = []
        for row in rows:
            entry = dict(row)
            if entry["detail"]:
                entry["detail"] = json.loads(entry["detail"])
            results.append(entry)
        return jsonify(results)

    @app.get("/api/multicloud")
    @require_roles("operations", "admin", "auditor", "warehouse")
    def multicloud_status():
        service_url = app.config["AZURE_FULFILLMENT_URL"].rstrip("/")
        if not service_url:
            return jsonify(status="not_configured"), 503

        headers = {"Accept": "application/json"}
        token = app.config["AZURE_FUNCTION_KEY"]
        if token:
            headers["x-functions-key"] = token

        upstream_request = Request(f"{azure_health_url(service_url)}", headers=headers)
        try:
            with urlopen(upstream_request, timeout=3) as response:
                upstream_body = json.loads(response.read().decode("utf-8"))
            return jsonify(status="connected", provider="Azure", upstream=upstream_body)
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
            return jsonify(status="unavailable", error=type(error).__name__), 502

    @app.post("/api/multicloud/sync")
    @require_roles("operations", "admin")
    def multicloud_sync():
        service_url = app.config["AZURE_FULFILLMENT_URL"].rstrip("/")
        if not service_url:
            return jsonify(status="not_configured"), 503

        payload = request.get_json(silent=True) or {}
        if not payload:
            return jsonify(error="se requiere un objeto JSON"), 400

        body = json.dumps(payload).encode("utf-8")
        headers = {"Accept": "application/json", "Content-Type": "application/json"}
        token = app.config["AZURE_FUNCTION_KEY"]
        if token:
            headers["x-functions-key"] = token

        upstream_request = Request(azure_event_url(service_url), data=body, headers=headers, method="POST")
        try:
            with urlopen(upstream_request, timeout=3) as response:
                upstream_body = json.loads(response.read().decode("utf-8"))
            return jsonify(status="synchronized", provider="Azure", upstream=upstream_body)
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
            return jsonify(status="unavailable", error=type(error).__name__), 502

    @app.get("/<path:asset_path>")
    def web_assets(asset_path):
        if (static_folder / asset_path).is_file():
            return send_from_directory(static_folder, asset_path)
        if (static_folder / "index.html").is_file() and not asset_path.startswith("api/"):
            return send_from_directory(static_folder, "index.html")
        return jsonify(error="not_found"), 404

    return app


def configured_database_target(config):
    """Prefer a managed PostgreSQL URL when the environment supplies one."""
    return config.get("DATABASE_URL") or config["DATABASE_PATH"]


def is_postgresql(database_target):
    return str(database_target).startswith(("postgresql://", "postgres://"))


class PostgreSQLConnection:
    """Small DB-API adapter so the application keeps one query surface.

    SQLite uses ``?`` placeholders while psycopg2 uses ``%s``. Keeping the
    conversion here makes local tests and managed RDS follow the same business
    logic without copying route implementations.
    """

    def __init__(self, raw_connection):
        self.raw_connection = raw_connection

    def execute(self, statement, params=()):
        from psycopg2.extras import RealDictCursor

        cursor = self.raw_connection.cursor(cursor_factory=RealDictCursor)
        cursor.execute(statement.replace("?", "%s"), params)
        return cursor

    def commit(self):
        self.raw_connection.commit()

    def close(self):
        self.raw_connection.close()


def connect(database_target):
    if is_postgresql(database_target):
        try:
            import psycopg2
        except ImportError as error:
            raise RuntimeError("PostgreSQL requires psycopg2-binary in the application image") from error
        return closing(PostgreSQLConnection(psycopg2.connect(database_target, connect_timeout=5)))
    connection = sqlite3.connect(database_target)
    connection.row_factory = sqlite3.Row
    return closing(connection)


def insert_and_return_id(connection, statement, params):
    if isinstance(connection, PostgreSQLConnection):
        row = connection.execute(f"{statement.strip().rstrip(';')} RETURNING id", params).fetchone()
        return row["id"]
    return connection.execute(statement, params).lastrowid


def is_integrity_error(error):
    if isinstance(error, sqlite3.IntegrityError):
        return True
    try:
        import psycopg2

        return isinstance(error, psycopg2.IntegrityError)
    except ImportError:
        return False


PORTAL_ROLES = {"customer", "sales", "warehouse", "operations", "admin", "auditor"}


def portal_user(database_path, user_id):
    if not user_id:
        return None
    with connect(database_path) as connection:
        row = connection.execute(
            """
            SELECT u.id, u.username, u.role, u.company_id, u.active, c.name AS company
            FROM portal_users AS u
            LEFT JOIN companies AS c ON c.id = u.company_id
            WHERE u.id = ?
            """,
            (user_id,),
        ).fetchone()
    if row is None or not row["active"]:
        return None
    return dict(row)


def current_portal_user(database_path):
    return portal_user(database_path, session.get("portal_user_id"))


def require_roles(*roles):
    allowed = set(roles)

    def decorator(endpoint):
        @wraps(endpoint)
        def wrapped(*args, **kwargs):
            user = current_portal_user(configured_database_target(current_app.config))
            if user is None:
                return jsonify(error="authentication_required"), 401
            if allowed and user["role"] not in allowed:
                return jsonify(error="insufficient_role"), 403
            g.portal_user = user
            return endpoint(*args, **kwargs)

        return wrapped

    return decorator


def write_audit(database_path, user_id, action, subject_type, subject_id=None, detail=None):
    with connect(database_path) as connection:
        connection.execute(
            """
            INSERT INTO audit_log(user_id, action, subject_type, subject_id, detail, created_at)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                user_id,
                action,
                subject_type,
                str(subject_id) if subject_id is not None else None,
                json.dumps(detail, separators=(",", ":")) if detail else None,
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        connection.commit()


def ensure_column(connection, table, column, definition):
    if isinstance(connection, PostgreSQLConnection):
        row = connection.execute(
            """
            SELECT EXISTS(
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = ? AND column_name = ?
            ) AS exists
            """,
            (table, column),
        ).fetchone()
        if not row["exists"]:
            connection.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
        return
    columns = {row["name"] for row in connection.execute(f"PRAGMA table_info({table})")}
    if column not in columns:
        connection.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def ensure_portal_bootstrap(app, database_path):
    """Create the first tenant and administrator only when a password is supplied.

    Production receives the password from a Secrets Manager-backed environment
    variable. Local tests provide it through their isolated configuration.
    """
    with connect(database_path) as connection:
        company = connection.execute(
            "SELECT id FROM companies WHERE slug = ?", ("tangamandapio",)
        ).fetchone()
        if company is None:
            try:
                company_id = insert_and_return_id(
                    connection,
                    "INSERT INTO companies(name, slug, created_at) VALUES (?, ?, ?)",
                    ("Tangamandapio S.A.C.", "tangamandapio", datetime.now(timezone.utc).isoformat()),
                )
            except Exception as error:
                if not is_integrity_error(error):
                    raise
                company = connection.execute(
                    "SELECT id FROM companies WHERE slug = ?", ("tangamandapio",)
                ).fetchone()
                company_id = company["id"]
        else:
            company_id = company["id"]

        password = app.config.get("BOOTSTRAP_ADMIN_PASSWORD", "")
        if password:
            connection.execute(
                """
                INSERT INTO portal_users(username, password_hash, role, company_id, active, created_at)
                VALUES (?, ?, 'admin', ?, 1, ?)
                ON CONFLICT(username) DO NOTHING
                """,
                (
                    app.config["BOOTSTRAP_ADMIN_USERNAME"].strip().lower(),
                    generate_password_hash(password),
                    company_id,
                    datetime.now(timezone.utc).isoformat(),
                ),
            )
        connection.commit()


def initialize_database(database_path):
    with connect(database_path) as connection:
        if isinstance(connection, PostgreSQLConnection):
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS companies (
                    id BIGSERIAL PRIMARY KEY,
                    name TEXT NOT NULL,
                    slug TEXT NOT NULL UNIQUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS portal_users (
                    id BIGSERIAL PRIMARY KEY,
                    username TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL CHECK (role IN ('customer','sales','warehouse','operations','admin','auditor')),
                    company_id BIGINT NOT NULL REFERENCES companies(id),
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS audit_log (
                    id BIGSERIAL PRIMARY KEY,
                    user_id BIGINT REFERENCES portal_users(id),
                    action TEXT NOT NULL,
                    subject_type TEXT NOT NULL,
                    subject_id TEXT,
                    detail TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS orders (
                    id BIGSERIAL PRIMARY KEY,
                    customer TEXT NOT NULL,
                    total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS outbox_events (
                    event_id TEXT PRIMARY KEY,
                    order_id BIGINT NOT NULL,
                    payload TEXT NOT NULL,
                    status TEXT NOT NULL CHECK (status IN ('pending', 'delivered', 'failed')),
                    attempts INTEGER NOT NULL DEFAULT 0,
                    last_error TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    delivered_at TIMESTAMPTZ
                )
                """
            )
            ensure_column(connection, "orders", "company_id", "BIGINT")
            ensure_column(connection, "orders", "created_by", "BIGINT")
            ensure_column(connection, "orders", "reference", "TEXT")
            ensure_column(connection, "orders", "status", "TEXT NOT NULL DEFAULT 'created'")
            connection.commit()
            return

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS companies (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                slug TEXT NOT NULL UNIQUE,
                created_at TEXT NOT NULL
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS portal_users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL CHECK (role IN ('customer','sales','warehouse','operations','admin','auditor')),
                company_id INTEGER NOT NULL,
                active INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL,
                FOREIGN KEY(company_id) REFERENCES companies(id)
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS audit_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                action TEXT NOT NULL,
                subject_type TEXT NOT NULL,
                subject_id TEXT,
                detail TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY(user_id) REFERENCES portal_users(id)
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                customer TEXT NOT NULL,
                total REAL NOT NULL CHECK (total >= 0),
                created_at TEXT NOT NULL
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS outbox_events (
                event_id TEXT PRIMARY KEY,
                order_id INTEGER NOT NULL,
                payload TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('pending', 'delivered', 'failed')),
                attempts INTEGER NOT NULL DEFAULT 0,
                last_error TEXT,
                created_at TEXT NOT NULL,
                delivered_at TEXT
            )
            """
        )
        ensure_column(connection, "orders", "company_id", "INTEGER")
        ensure_column(connection, "orders", "created_by", "INTEGER")
        ensure_column(connection, "orders", "reference", "TEXT")
        ensure_column(connection, "orders", "status", "TEXT NOT NULL DEFAULT 'created'")
        connection.commit()


def azure_event_url(service_url):
    base = service_url.rstrip("/")
    return base if base.endswith("/api/fulfillment/events") else f"{base}/api/fulfillment/events"


def azure_health_url(service_url):
    base = service_url.rstrip("/")
    if base.endswith("/api/fulfillment/events"):
        base = base[: -len("/api/fulfillment/events")]
    return f"{base}/api/health" if ".azurewebsites.net" in base else f"{base}/health"


def dispatch_outbox_event(app, database_path, event_id):
    """Deliver an already committed event. A failure never rolls back the order."""
    with connect(database_path) as connection:
        row = connection.execute(
            "SELECT payload, attempts FROM outbox_events WHERE event_id = ?", (event_id,)
        ).fetchone()
    if row is None:
        return {"status": "not_found", "event_id": event_id}

    service_url = app.config["AZURE_FULFILLMENT_URL"].rstrip("/")
    if not service_url:
        return {"status": "pending", "event_id": event_id, "reason": "azure_not_configured"}

    headers = {"Accept": "application/json", "Content-Type": "application/json"}
    token = app.config["AZURE_FUNCTION_KEY"]
    if token:
        headers["x-functions-key"] = token

    try:
        upstream_request = Request(
            azure_event_url(service_url),
            data=row["payload"].encode("utf-8"),
            headers=headers,
            method="POST",
        )
        with urlopen(upstream_request, timeout=5) as response:
            upstream_body = json.loads(response.read().decode("utf-8"))
        status = upstream_body.get("status", "accepted")
        if status not in {"queued", "duplicate", "accepted"}:
            raise ValueError("unexpected_upstream_status")
        with connect(database_path) as connection:
            connection.execute(
                """
                UPDATE outbox_events
                SET status = 'delivered', attempts = attempts + 1, last_error = NULL, delivered_at = ?
                WHERE event_id = ?
                """,
                (datetime.now(timezone.utc).isoformat(), event_id),
            )
            connection.commit()
        app.extensions["metrics"]["outbox_delivered_total"] += 1
        return {"status": "delivered", "event_id": event_id, "upstream": status}
    except (HTTPError, URLError, TimeoutError, ValueError, json.JSONDecodeError) as error:
        with connect(database_path) as connection:
            connection.execute(
                """
                UPDATE outbox_events
                SET status = 'failed', attempts = attempts + 1, last_error = ?
                WHERE event_id = ?
                """,
                (type(error).__name__, event_id),
            )
            connection.commit()
        app.extensions["metrics"]["outbox_failed_total"] += 1
        return {"status": "pending", "event_id": event_id, "reason": type(error).__name__}


app = create_app()


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", "8080")))
